apiVersion: v1
kind: Service
metadata:
  name: mesh-istio-bluegreen
spec:
  selector:
    app: mesh-istio-bluegreen
  ports:
    - name: http-admin
      protocol: TCP
      port: 9085
      targetPort: 9085
