apiVersion: pipecd.dev/v1beta1
kind: LambdaFunction
spec:
  name: SimpleFunction
  image: ecr.ap-northeast-1.amazonaws.com/lambda-test:v0.0.1
  runtime: nodejs12.x
  handler: app.lambdaHandler
  tags:
    app: simple
