# Deploy a kustomize package that just uses the local bases from the same Git repository
# without using pipeline.
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
    kustomizeVersion: 3.5.5
