apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      pipecd.dev/variant: primary
  replicas: 4 
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: nginx
        pipecd.dev/variant: primary
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80