# Quick sync by rolling out the new version and switching all traffic to it.
# https://docs.aws.amazon.com/lambda/latest/dg/configuration-versions.html
apiVersion: pipecd.dev/v1beta1
kind: LambdaApp
spec:
  input:
    # Lambda code sourced from another Git repository.
    git: git@github.com:org/source-repo.git
    path: lambdas/helloworld
    ref: v1.0.0
