# Using version, alias, additional version to do canary, bluegreen.
# https://docs.aws.amazon.com/lambda/latest/dg/configuration-aliases.html
apiVersion: pipecd.dev/v1beta1
kind: LambdaApp
spec:
  input:
    # Where to fetch the source code to create lambda package.
    git: git@github.com:org/source-repo.git
    path: lambdas/demoapp
    ref: v1.0.0
  pipeline:
    stages:
      # Deploy workloads of the new version.
      # But this is still receiving no traffic.
      - name: LAMBDA_CANARY_ROLLOUT
      # Change the traffic routing state where
      # the new version will receive 100% of the traffic as soon as possible.
      # This is known as blue-green strategy.
      - name: LAMBDA_TRAFFIC_ROUTING
        with:
          canary: 100
      # Optional: We can also add an ANALYSIS stage to verify the new version.
      # If this stage finds any not good metrics of the new version,
      # a rollback process to the previous version will be executed.
      - name: ANALYSIS
