# Deploy a helm chart sourced from the same Git repository
# without using pipeline.
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
    # Helm chart sourced from current Git repo.
    helmChart:
      path: ../../local/helm-charts/helloworld
    helmOptions:
      releaseName: helm-local-chart
      valueFiles:
        - values.yaml
    helmVersion: 3.1.1
